### ISSUE TITLE
Undoing future plan()

### ISSUE THREAD

**Issue by HenrikBengtsson** [monty-se/PINstimation#1]
Hi, congrats to your CRAN release.

# Issue

I noticed that you use:

https://github.com/monty-se/PINstimation/blob/ffe8da4c5d11b28dce73748291a26a557dce5a5d/R/data_aggregation.R#L374-L381

to "undo" the future plan.  There are two problems with this approach:

1. The user might have another plan than 'sequential' set before they call your function
2. If there's an error before you get to undo the plan, the plan will never be reset

# Solution

A better, straightforward approach is explained Section 'For package developers' of  [`?future::plan`](https://future.futureverse.org/reference/plan.html).

No rush, but please consider fixing this for your next release.

**Comment by monty-se** [comment]
Thanks @HenrikBengtsson, 
I have just performed, and tested the changes to the code here on Github. 
It should now reset the plan to its initial value upon function exit.
