### ISSUE TITLE
Please do not change future options 

### ISSUE THREAD

**Issue by HenrikBengtsson** [monty-se/PINstimation#6]
Hello. Please do _not_ set future options from within your package, as in:

https://github.com/monty-se/PINstimation/blob/db52236301efed26da491a48efa4a9c5c6886bf8/R/zzz.R#L9

This might have unintended side effects for other packages and risk producing incorrect results elsewhere. R options are meant for end-users, not developers. If you need to tweak the settings, please do so temporarily, as explained in https://future.futureverse.org/articles/future-7-for-package-developers.html#avoid-changing-the-future-options.

**Comment by monty-se** [comment]
@HenrikBengtsson Thanks for raising the issue. I have deleted the line that modifies the future options from the within the package. I might reuse the solution you have suggested in case I need to tweak the options in the future.
